In [21]:
import pandas as pd
import datetime
import yfinance as yf
from decimal import Decimal

In [22]:
today = datetime.datetime.now().strftime('%Y-%m-%d')

In [23]:
# Lista de tickers com a extensÃ£o .SA
tickers = ['B3SA3.SA','PDGR3.SA','VALE3.SA','BBDC4.SA','HAPV3.SA','PETR4.SA','AZUL4.SA','USIM5.SA','COGN3.SA',
'LREN3.SA','ITUB4.SA','ABEV3.SA','ASAI3.SA','ANIM3.SA','RAIL3.SA','ITSA4.SA','GGBR4.SA','PRIO3.SA','RAIZ4.SA',
'CSNA3.SA','CMIN3.SA','MGLU3.SA','IFCM3.SA','BBAS3.SA','CMIG4.SA','POMO4.SA','MRVE3.SA','CVCB3.SA','CRFB3.SA',
'BRAV3.SA','CSAN3.SA','PETZ3.SA','STBP3.SA','PETR3.SA','CBAV3.SA','CPLE6.SA','WEGE3.SA','ELET3.SA','RENT3.SA',
'JBSS3.SA','ENEV3.SA','BPAC11.SA','BBDC3.SA','MRFG3.SA','BBSE3.SA','CYRE3.SA','GOAU4.SA','EQTL3.SA','VAMO3.SA',
'TIMS3.SA','YDUQ3.SA','VBBR3.SA','UGPA3.SA','RAPT4.SA','PCAR3.SA','QUAL3.SA','BEEF3.SA','SUZB3.SA','BRAP4.SA',
'CCRO3.SA','NTCO3.SA','RDOR3.SA','BRFS3.SA','EMBR3.SA','DXCO3.SA','RADL3.SA','LWSA3.SA','IGTI11.SA','IGTI11.SA',
'CXSE3.SA','KLBN11.SA','MLAS3.SA','AURE3.SA','CURY3.SA','MULT3.SA','MOVI3.SA','TOTS3.SA','SBSP3.SA','SIMH3.SA',
'GFSA3.SA','TEND3.SA','GOLL4.SA','JHSF3.SA','CPLE3.SA','BRKM5.SA','JFEN3.SA','LJQQ3.SA','ENGI11.SA','AESB3.SA',
'ALPA4.SA','FLRY3.SA','VIVA3.SA','GGPS3.SA','ALOS3.SA','GMAT3.SA','TRPL4.SA','BPAN4.SA','AMER3.SA','SLCE3.SA',
'VVEO3.SA','INTB3.SA','PSSA3.SA','HYPE3.SA','ECOR3.SA','BHIA3.SA','DIRR3.SA','SRNA3.SA','EZTC3.SA','AZZA3.SA',
'SAPR11.SA','HBSA3.SA','CEAB3.SA','CLSA3.SA','CPFE3.SA','SANB11.SA','VIVT3.SA','ONCO3.SA','TAEE11.SA','AZEV4.SA',
'SAPR4.SA','CSMG3.SA','RECV3.SA','SMTO3.SA','CASH3.SA','SMFT3.SA','PORT3.SA','POSI3.SA','SBFG3.SA','RCSL3.SA',
'AMBP3.SA','FESA4.SA','BRSR6.SA','ELET6.SA','MYPK3.SA','KLBN4.SA','KEPL3.SA','LIGT3.SA','JALL3.SA','ZAMP3.SA',
'RANI3.SA','VULC3.SA','DASA3.SA','HBRE3.SA','GRND3.SA','IRBR3.SA','OIBR3.SA','EGIE3.SA','AERI3.SA','TTEN3.SA',
'GUAR3.SA','EVEN3.SA','SEQL3.SA','LAVV3.SA','TRIS3.SA','NEOE3.SA','ITUB3.SA','MATD3.SA','MILS3.SA','FIQE3.SA',
'ARML3.SA','PLPL3.SA','MTRE3.SA','MELK3.SA','MDIA3.SA','PFRM3.SA','SOJA3.SA','PGMN3.SA','PTBL3.SA','AZEV3.SA',
'USIM3.SA','ABCB4.SA','CAML3.SA','ALUP11.SA','ODPV3.SA','ENJU3.SA','MEAL3.SA','ORVR3.SA','OPCT3.SA','LEVE3.SA',
'SYNE3.SA','EQMA3B.SA','RCSL4.SA','BRIT3.SA','CSED3.SA','VTRU3.SA','TUPY3.SA','AGXY3.SA','HBOR3.SA','MDNE3.SA',
'MBLY3.SA','VITT3.SA','LOGG3.SA','PNVL3.SA','WIZC3.SA','BMGB4.SA','VLID3.SA','SEER3.SA','FRAS3.SA','POMO3.SA',
'AGRO3.SA','SHUL4.SA','CMIG3.SA','TASA4.SA','DESK3.SA','KLBN3.SA','TRAD3.SA','NGRD3.SA','UNIP6.SA','ETER3.SA',
'JSLG3.SA','TAEE4.SA','BRBI11.SA','BMOB3.SA','BLAU3.SA','AMAR3.SA','PRNR3.SA','BRAP3.SA','KRSA3.SA','ROMI3.SA',
'SAPR3.SA','PINE4.SA','LPSB3.SA','PMAM3.SA','TGMA3.SA','ALPK3.SA','BOBR4.SA','TFCO4.SA','VIVR3.SA','ESPA3.SA',
'SANB4.SA','ELMD3.SA','SHOW3.SA','SANB3.SA','GGBR3.SA','RNEW4.SA','CTSA4.SA','TAEE3.SA','RNEW3.SA','TCSA3.SA',
'ITSA3.SA','DMVF3.SA','LUPA3.SA','CAMB3.SA','ATOM3.SA','DEXP3.SA','TECN3.SA','PDTC3.SA','ALLD3.SA','TPIS3.SA',
'LAND3.SA','GOAU3.SA','AALR3.SA','TASA3.SA','BIOM3.SA','INEP4.SA','RAPT3.SA','DASA11.SA','HAGA3.SA','CSUD3.SA',
'NINJ3.SA','RPMG3.SA','IGTI3.SA','IGTI3.SA','ALUP4.SA','DOTZ3.SA','EALT4.SA','BMEB4.SA','UCAS3.SA','BRSR3.SA',
'CRPG5.SA','EUCA4.SA','LVTC3.SA','BEES3.SA','EPAR3.SA','BRKM3.SA','BAHI3.SA','ATMP3.SA','VSTE3.SA','UNIP3.SA',
'RSID3.SA','ESTR4.SA','EMAE4.SA','INEP3.SA','CEBR5.SA','CEBR3.SA','PTNT4.SA','BEES4.SA','WHRL4.SA','BPAC3.SA',
'ENGI4.SA','UNIP5.SA','HAGA4.SA','TELB3.SA','WEST3.SA','RSUL4.SA','TELB4.SA','MTSA4.SA','CEBR6.SA','OIBR4.SA',
'ALUP3.SA','COCE5.SA','MGEL4.SA','DEXP4.SA','TRPL3.SA','MNPR3.SA','CGRA4.SA','ENGI3.SA','AMAR11.SA','CLSC4.SA',
'ALPA3.SA','WHRL3.SA','NUTR3.SA','LOGN3.SA','EQPA3.SA','SCAR3.SA','CPLE5.SA','AVLL3.SA','FRIO3.SA','BAZA3.SA',
'OSXB3.SA','BPAC5.SA','OFSA3.SA','FESA3.SA','CGAS5.SA','BGIP4.SA','CTSA3.SA','CTKA3.SA','EKTR4.SA','REDE3.SA',
'NEXP3.SA','RDNI3.SA','DTCY3.SA','RNEW11.SA','WLMM4.SA','CRPG6.SA','CEDO4.SA','EALT3.SA','RPAD3.SA','CEEB3.SA',
'PLAS3.SA','FHER3.SA','BIOM11.SA','GEPA4.SA','BGIP3.SA','PATI3.SA','SNSY5.SA','PINE3.SA','DOHL4.SA','AZEV11.SA',
'BMKS3.SA','AHEB3.SA','CBEE3.SA','EUCA3.SA','PTNT3.SA','GSHP3.SA','BSLI4.SA','IGTI4.SA','IGTI4.SA','BSLI3.SA',
'EQPA5.SA','HOOT4.SA','FIEI3.SA','CGRA3.SA','PSVM11.SA','MERC4.SA','MNDL3.SA','CEDO3.SA','BRSR5.SA','PEAB4.SA',
'BMIN4.SA','PEAB3.SA','HBTS5.SA','CEEB5.SA','AFLT3.SA','PPLA11.SA','BMEB3.SA','SNSY3.SA','BALM3.SA','RPAD5.SA',
'CTKA4.SA','GEPA3.SA','MAPT4.SA','BRKM6.SA','BAUH4.SA','PATI4.SA','TKNO4.SA','TEKA4.SA','RPAD6.SA','HETA4.SA',
'PINE11.SA','NORD3.SA','BALM4.SA','CLSC3.SA','LIPR3.SA','AHEB5.SA','MWET4.SA','MRSA3B.SA','ELET5.SA','JOPA3.SA',
'LUXM4.SA','MRSA6B.SA','ENMT4.SA','SOND5.SA','BMIN3.SA',
]

In [24]:
acoes = yf.download(tickers, start='2010-01-01', end=today)
print(acoes.head())

[*********************100%***********************]  401 of 401 completed

6 Failed downloads:
['PINE11.SA', 'AMAR11.SA', 'DASA11.SA', 'BIOM11.SA', 'AZEV11.SA']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
['EQPA3.SA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2010-01-01 -> 2024-10-17)')

Price                     Adj Close                                        \
Ticker                     AALR3.SA  ABCB4.SA  ABEV3.SA AERI3.SA AESB3.SA
Date
2010-01-04 00:00:00+00:00       NaN  3.975713  3.618472      NaN      NaN
2010-01-05 00:00:00+00:00       NaN  4.081947  3.639759      NaN      NaN
2010-01-06 00:00:00+00:00       NaN  4.149551  3.676889      NaN      NaN
2010-01-07 00:00:00+00:00       NaN  4.088385  3.694153      NaN      NaN
2010-01-08 00:00:00+00:00       NaN  4.056193  3.687058      NaN      NaN

Price                                                                       \
Ticker                     AFLT3.SA  AGRO3.SA AGXY3.SA   AHEB3.SA AHEB5.SA
Date
2010-01-04 00:00:00+00:00  6.958521  5.021648      NaN  22.192442  9.84313
2010-01-05 00:00:00+00:00  6.958521  5.021648      NaN  22.192442  9.84313
2010-01-06 00:00:00+00:00  6.958521  5.021648      NaN  22.192442  9.84313
2010-01-07 00:00:00+00:00  6.958521  5.164421      NaN  22.192442  9.84313
2010-01-08 00:00:00+00:00  6.958521  5.164421      NaN  22.192442  9.84313

Price                      ...   Volume                                      \
Ticker                     ... VULC3.SA VVEO3.SA WEGE3.SA WEST3.SA WHRL3.SA
Date                       ...
2010-01-04 00:00:00+00:00  ...     2027      NaN  3776812      NaN        0
2010-01-05 00:00:00+00:00  ...     3749      NaN  1429064      NaN        0
2010-01-06 00:00:00+00:00  ...     1925      NaN  4106024      NaN        0
2010-01-07 00:00:00+00:00  ...      506      NaN   939640      NaN        0
2010-01-08 00:00:00+00:00  ...        0      NaN  2199028      NaN        0

Price
Ticker                    WHRL4.SA WIZC3.SA WLMM4.SA YDUQ3.SA ZAMP3.SA
Date
2010-01-04 00:00:00+00:00    21100      NaN   285000   118200      NaN
2010-01-05 00:00:00+00:00    34300      NaN        0    45300      NaN
2010-01-06 00:00:00+00:00    21600      NaN    23500    48900      NaN
2010-01-07 00:00:00+00:00     4300      NaN     7000    38400      NaN
2010-01-08 00:00:00+00:00    17300      NaN    16500    33000      NaN

[5 rows x 2406 columns]

In [27]:
acoes_tabular = acoes.stack(level=1).reset_index()

# Renomear colunas para facilitar entendimento
acoes_tabular.columns = ['Date', 'Ticker', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']

acoes_tabular = acoes_tabular.rename(columns={
    'Ticker': 'Acoes',
    'Open': 'Abertura',
    'High': 'Maxima',
    'Low': 'Minima',
    'Close': 'Fechamento',
    'Adj Close': 'Fechamento Ajustado',
    'Volume': 'Volume (Quantidade)'
})

C:\Users\paulo\AppData\Local\Temp\ipykernel_13612\1658851256.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  acoes_tabular = acoes.stack(level=1).reset_index()

In [28]:
tickers = acoes_tabular['Acoes'].unique()

# Inicializa DataFrame para armazenar todos os dividendos
dividendos_df = pd.DataFrame()

# Itera sobre os tickers e obtÃ©m dividendos
for ticker in tickers:
    stock = yf.Ticker(ticker)
    dividendos = stock.dividends
    dividendos = dividendos.reset_index()
    dividendos['Acoes'] = ticker  # Adiciona o ticker aos dividendos
    dividendos_df = pd.concat([dividendos_df, dividendos])  # Concatena os dividendos

# Renomear colunas do DataFrame de dividendos
dividendos_df.columns = ['Date', 'Dividendo', 'Acoes']

# Converte a coluna 'Date' para datetime, se necessÃ¡rio
acoes_tabular['Date'] = pd.to_datetime(acoes_tabular['Date'])
dividendos_df['Date'] = pd.to_datetime(dividendos_df['Date'])

# Faz o merge dos dividendos com o DataFrame 'acoes_tabular'
acoes_com_dividendos = pd.merge(acoes_tabular, dividendos_df, on=['Date', 'Acoes'], how='left')

                             Date     Acoes   Abertura     Maxima     Minima  \
0       2010-01-04 00:00:00+00:00  ABCB4.SA   3.975713   8.847957   8.898107
1       2010-01-04 00:00:00+00:00  ABEV3.SA   3.618472   6.113138   6.121129
2       2010-01-04 00:00:00+00:00  AFLT3.SA   6.958521  15.000000  15.000000
3       2010-01-04 00:00:00+00:00  AGRO3.SA   5.021648  10.200000  10.250000
4       2010-01-04 00:00:00+00:00  AHEB3.SA  22.192442  22.192442  22.192442
...                           ...       ...        ...        ...        ...
1159606 2024-10-16 00:00:00+00:00  WHRL4.SA   4.430000   4.430000   4.460000
1159607 2024-10-16 00:00:00+00:00  WIZC3.SA   5.980000   5.980000   6.050000
1159608 2024-10-16 00:00:00+00:00  WLMM4.SA  32.189999  32.189999  32.250000
1159609 2024-10-16 00:00:00+00:00  YDUQ3.SA  10.580000  10.580000  10.800000
1159610 2024-10-16 00:00:00+00:00  ZAMP3.SA   2.550000   2.550000   2.570000

         Fechamento  Fechamento Ajustado  Volume (Quantidade)  Dividendo
0          8.597205             8.597205             280835.0        NaN
1          5.873407             5.932941             818417.0        NaN
2         15.000000            15.000000                  0.0        NaN
3         10.200000            10.250000               6000.0        NaN
4         22.192442            22.192442                  0.0        NaN
...             ...                  ...                  ...        ...
1159606    4.410000             4.430000               3400.0        NaN
1159607    5.920000             6.050000             230300.0        NaN
1159608   31.200001            31.209999                900.0        NaN
1159609   10.210000            10.220000            5184100.0        NaN
1159610    2.480000             2.540000             669100.0        NaN

[1159611 rows x 9 columns]

In [29]:
# Exibindo as primeiras 5 linhas do DataFrame ordenado
acoes_com_dividendos.head()

,Date,Acoes,Abertura,Maxima,Minima,Fechamento,Fechamento Ajustado,Volume (Quantidade),Dividendo
0,2010-01-04 00:00:00+00:00,ABCB4.SA,3.975713,8.847957,8.898107,8.597205,8.597205,280835.0,NaN
1,2010-01-04 00:00:00+00:00,ABEV3.SA,3.618472,6.113138,6.121129,5.873407,5.932941,818417.0,NaN
2,2010-01-04 00:00:00+00:00,AFLT3.SA,6.958521,15.000000,15.000000,15.000000,15.000000,0.0,NaN
3,2010-01-04 00:00:00+00:00,AGRO3.SA,5.021648,10.200000,10.250000,10.200000,10.250000,6000.0,NaN
4,2010-01-04 00:00:00+00:00,AHEB3.SA,22.192442,22.192442,22.192442,22.192442,22.192442,0.0,NaN

In [30]:
colunas_float = ['Abertura', 'Maxima', 'Minima', 'Fechamento', 'Fechamento Ajustado', 'Volume (Quantidade)','Dividendo']

In [33]:
# FunÃ§Ã£o para converter para string e substituir o ponto por vÃ­rgula
def formatar_decimal(valor):
    return str(valor).replace('.', ',') if valor is not None else ''

# Aplicar a formataÃ§Ã£o para cada coluna de float
for coluna in colunas_float:
    acoes_com_dividendos[coluna] = acoes_com_dividendos[coluna].apply(formatar_decimal)

In [34]:
# Salvar o DataFrame em um arquivo CSV, usando vÃ­rgula como delimitador
acoes_com_dividendos.to_csv('acoes.csv', sep=';', index=False, decimal=',')

In [36]:
acoes_com_dividendos.head()

,Date,Acoes,Abertura,Maxima,Minima,Fechamento,Fechamento Ajustado,Volume (Quantidade),Dividendo
0,2010-01-04 00:00:00+00:00,ABCB4.SA,"3,9757134914398193","8,847956657409668","8,898106575012207","8,59720516204834","8,59720516204834","280835,0",nan
1,2010-01-04 00:00:00+00:00,ABEV3.SA,"3,618472099304199","6,113138198852539","6,121129035949707","5,873406887054443","5,93294095993042","818417,0",nan
2,2010-01-04 00:00:00+00:00,AFLT3.SA,"6,958521366119385","15,0","15,0","15,0","15,0","0,0",nan
3,2010-01-04 00:00:00+00:00,AGRO3.SA,"5,021648406982422","10,199999809265137","10,25","10,199999809265137","10,25","6000,0",nan
4,2010-01-04 00:00:00+00:00,AHEB3.SA,"22,192441940307617","22,192441940307617","22,192441940307617","22,192441940307617","22,192441940307617","0,0",nan